
import { Locale } from '@/i18n.config'
import { getDictionary } from '@/lib/dictionaries'

export default async function TermsPage({ params: { lang } }: { params: { lang: Locale } }) {
  const dict = await getDictionary(lang)

  return (
    <div className="container mx-auto max-w-4xl py-12">
      <article className="prose dark:prose-invert">
        <h1 className="mb-8">{dict.footer.terms}</h1>
        
        <p className="mb-4">
          Welcome to Draftright! By using our application, you agree to these Terms of Use. These terms govern your access to and use of our email drafting service.
        </p>

        <h2 className="mb-4">1. Description of Service</h2>
        <p className="mb-4">
          Draftright provides a tool that generates email drafts based on user-provided inputs and scenarios. The service is intended to assist users in creating professional and personal communications. The output is generated by an automated system and should be reviewed for accuracy and appropriateness before use.
        </p>

        <h2 className="mb-4">2. User Responsibilities</h2>
        <p className="mb-4">
          You are solely responsible for the input you provide and for the final content of any email you send. You agree not to use the service to generate content that is unlawful, harmful, defamatory, obscene, or otherwise objectionable. You are also responsible for verifying the accuracy of the generated drafts.
        </p>

        <h2 className="mb-4">3. Intellectual Property</h2>
        <p className="mb-4">
          You retain any rights you have to the content you input into the service. By using the service, you grant us a temporary, non-exclusive license to use your input solely to generate the email draft for you. We do not claim any ownership over the content you provide or the drafts that are generated.
        </p>

        <h2 className="mb-4">4. Disclaimer of Warranties</h2>
        <p className="mb-4">
          The service is provided on an "as is" and "as available" basis. Draftright makes no warranties of any kind, express or implied, regarding the accuracy, reliability, or suitability of the generated email drafts. We do not guarantee that the service will be error-free or uninterrupted.
        </p>

        <h2 className="mb-4">5. Limitation of Liability</h2>
        <p className="mb-4">
          Draftright shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service, including any reliance on the accuracy of the generated content.
        </p>
      </article>
    </div>
  )
}
